// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import playlist "github.com/samuelrey/spot-the-bot/playlist"

// Creator is an autogenerated mock type for the Creator type
type Creator struct {
	mock.Mock
}

// Create provides a mock function with given fields: playlistName
func (_m *Creator) Create(playlistName string) (*playlist.Playlist, error) {
	ret := _m.Called(playlistName)

	var r0 *playlist.Playlist
	if rf, ok := ret.Get(0).(func(string) *playlist.Playlist); ok {
		r0 = rf(playlistName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*playlist.Playlist)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(playlistName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
