// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	message "github.com/samuelrey/spot-the-bot/message"
	mock "github.com/stretchr/testify/mock"
)

// IProvider is an autogenerated mock type for the IProvider type
type IProvider struct {
	mock.Mock
}

// GetRotationRepository provides a mock function with given fields:
func (_m *IProvider) GetRotationRepository() message.IRotationRepository {
	ret := _m.Called()

	var r0 message.IRotationRepository
	if rf, ok := ret.Get(0).(func() message.IRotationRepository); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(message.IRotationRepository)
		}
	}

	return r0
}
