// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Messager is an autogenerated mock type for the Messager type
type Messager struct {
	mock.Mock
}

// DirectMessage provides a mock function with given fields: recipientID, content
func (_m *Messager) DirectMessage(recipientID string, content string) error {
	ret := _m.Called(recipientID, content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(recipientID, content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Reply provides a mock function with given fields: content
func (_m *Messager) Reply(content string) error {
	ret := _m.Called(content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
