// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Replyer is an autogenerated mock type for the Replyer type
type Replyer struct {
	mock.Mock
}

// Reply provides a mock function with given fields: content
func (_m *Replyer) Reply(content string) error {
	ret := _m.Called(content)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
