// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import message "github.com/samuelrey/spot-the-bot/message"
import mock "github.com/stretchr/testify/mock"

// RotationUpserter is an autogenerated mock type for the RotationUpserter type
type RotationUpserter struct {
	mock.Mock
}

// Upsert provides a mock function with given fields: _a0
func (_m *RotationUpserter) Upsert(_a0 message.Rotation) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(message.Rotation) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
