// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	message "github.com/samuelrey/spot-the-bot/message"
	mock "github.com/stretchr/testify/mock"
)

// RotationFinder is an autogenerated mock type for the RotationFinder type
type RotationFinder struct {
	mock.Mock
}

// FindOne provides a mock function with given fields: _a0
func (_m *RotationFinder) FindOne(_a0 string) (*message.Rotation, error) {
	ret := _m.Called(_a0)

	var r0 *message.Rotation
	if rf, ok := ret.Get(0).(func(string) *message.Rotation); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*message.Rotation)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
